version: "3"
services:
  service_api:
    container_name: service_api
    image: service_api
    build:
      context: ./services
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    depends_on:
      - mongo
    networks:
      - about_net
  mongo:
    container_name: mongoaboutbook
    image: mongo
    ports:
      - "27018:27018"
    networks:
      - about_net
  webapp:
    container_name: webapp
    build:
      context: ./webapp
      dockerfile: Dockerfile
    ports:
      - 8000:80
    depends_on:
      - service_api
    networks:
      - about_net
networks:
  about_net:
